# Generated by Django 3.2.4 on 2021-07-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_store1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.FileField(upload_to='')),
                ('title', models.CharField(default='my file', max_length=120)),
                ('wpm', models.IntegerField(blank=True, null=True)),
                ('pausesandfillerwords', models.IntegerField(blank=True, null=True)),
                ('pitch', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('pronunciation', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('spotwords', models.IntegerField(blank=True, null=True)),
                ('sensitivewords', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Audio_store1',
            },
        ),
    ]
