# Generated by Django 3.2.4 on 2021-07-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hrplatform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio_store1',
            old_name='pausesandfillerwords',
            new_name='pauses',
        ),
    ]
