# Generated by Django 3.2.4 on 2021-07-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrplatform', '0002_rename_pausesandfillerwords_audio_store1_pauses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio_store1',
            old_name='pitch',
            new_name='meanpitch',
        ),
        migrations.RenameField(
            model_name='audio_store1',
            old_name='record',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='audio_store1',
            name='title',
        ),
        migrations.AddField(
            model_name='audio_store1',
            name='fillerwords',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='audio_store1',
            name='sensitivewords',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='audio_store1',
            name='spotwords',
            field=models.CharField(default='', max_length=120),
        ),
    ]
